#!/usr/bin/env bash
# codependent — config generator
# Usage: generate-configs.sh [--config FILE] [--verify]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

VERIFY_MODE=false
CONFIG_FILE="$CODEPENDENT_ROOT/resilience.conf"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config) CONFIG_FILE="$2"; shift 2 ;;
        --verify) VERIFY_MODE=true; shift ;;
        *) shift ;;
    esac
done

load_config "$CONFIG_FILE"

GUARDRAILS="$CODEPENDENT_ROOT/guardrails.md"
TOOLS_DIR="$CODEPENDENT_ROOT/tools"

generate_for_tool() {
    local tool="$1"
    local output_file="$2"
    local template="$TOOLS_DIR/$tool/template.md"
    local header="# Generated by codependent/generate-configs.sh — do not edit directly"

    {
        echo "$header"
        echo ""
        cat "$GUARDRAILS"
        echo ""
        if [[ -f "$template" ]]; then
            echo ""
            cat "$template"
        fi
    } > "$output_file"
}

verify_for_tool() {
    local tool="$1"
    local output_file="$2"

    if [[ ! -f "$output_file" ]]; then
        echo "DRIFT: $output_file does not exist" >&2
        return 1
    fi

    # Generate expected content to a temp file
    local expected_file
    expected_file=$(mktemp)
    generate_for_tool "$tool" "$expected_file"

    # Compare
    if ! diff -q "$expected_file" "$output_file" &>/dev/null; then
        echo "DRIFT: $output_file differs from expected" >&2
        rm -f "$expected_file"
        return 1
    fi

    rm -f "$expected_file"
    return 0
}

# Discover projects — look for directories that contain a .claude subdirectory
IFS=',' read -ra roots <<< "${CFG_project_roots:-~/Projects}"
PROJECTS=()
for root in "${roots[@]}"; do
    root="${root/#\~/$HOME}"
    root="$(echo "$root" | xargs)"  # trim whitespace
    if [[ -d "$root" ]]; then
        # Check if root itself has .claude
        if [[ -d "$root/.claude" ]]; then
            PROJECTS+=("$root")
        fi
        # Also check subdirectories
        while IFS= read -r proj_claude_dir; do
            PROJECTS+=("$(dirname "$proj_claude_dir")")
        done < <(find "$root" -maxdepth 2 -mindepth 1 -type d -name ".claude" 2>/dev/null)
    fi
done

# Deduplicate
UNIQUE_PROJECTS=()
declare -A seen_projects 2>/dev/null || true
for p in "${PROJECTS[@]}"; do
    if [[ -z "${seen_projects[$p]:-}" ]]; then
        seen_projects[$p]=1
        UNIQUE_PROJECTS+=("$p")
    fi
done
PROJECTS=("${UNIQUE_PROJECTS[@]}")

DRIFT_FOUND=false

for project in "${PROJECTS[@]}"; do
    # Codex → AGENTS.md
    if "$VERIFY_MODE"; then
        verify_for_tool "codex" "$project/AGENTS.md" || DRIFT_FOUND=true
    else
        generate_for_tool "codex" "$project/AGENTS.md"
    fi

    # Aider → CONVENTIONS.md
    if "$VERIFY_MODE"; then
        verify_for_tool "aider" "$project/CONVENTIONS.md" || DRIFT_FOUND=true
    else
        generate_for_tool "aider" "$project/CONVENTIONS.md"
    fi

    # Cursor → .cursor/rules/guardrails.mdc
    if "$VERIFY_MODE"; then
        verify_for_tool "cursor" "$project/.cursor/rules/guardrails.mdc" || DRIFT_FOUND=true
    else
        mkdir -p "$project/.cursor/rules"
        generate_for_tool "cursor" "$project/.cursor/rules/guardrails.mdc"
    fi

    # Claude → .claude/CLAUDE.md (only per-project, not the user global CLAUDE.md)
    if "$VERIFY_MODE"; then
        verify_for_tool "claude" "$project/.claude/CLAUDE.md" || DRIFT_FOUND=true
    else
        mkdir -p "$project/.claude"
        generate_for_tool "claude" "$project/.claude/CLAUDE.md"
    fi
done

if "$VERIFY_MODE"; then
    if "$DRIFT_FOUND"; then
        echo "Config drift detected. Run generate-configs.sh to fix." >&2
        exit 1
    else
        echo "All configs in sync."
        exit 0
    fi
else
    echo "Generated configs for ${#PROJECTS[@]} projects."
fi
