#!/usr/bin/env bash

setup_generate_env() {
    export TEST_OUTPUT_DIR="$(mktemp -d)"
    export TEST_PROJECT_DIR="$(mktemp -d)"
    mkdir -p "$TEST_PROJECT_DIR/.claude"
    export TEST_CONF="$(mktemp)"
    cat > "$TEST_CONF" <<CONF
project_roots=$TEST_PROJECT_DIR
CONF
}

teardown_generate_env() {
    rm -rf "$TEST_OUTPUT_DIR" "$TEST_PROJECT_DIR" "$TEST_CONF"
}

test_generate_produces_agents_md() {
    setup_generate_env
    source "$PROJECT_ROOT/lib.sh"
    load_config "$TEST_CONF"
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    assert_file_exists "$TEST_PROJECT_DIR/AGENTS.md"
    local content
    content=$(cat "$TEST_PROJECT_DIR/AGENTS.md")
    assert_contains "$content" "Generated by"
    teardown_generate_env
}

test_generate_is_deterministic() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    local hash1
    hash1=$(sha256sum "$TEST_PROJECT_DIR/AGENTS.md" | awk '{print $1}')
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    local hash2
    hash2=$(sha256sum "$TEST_PROJECT_DIR/AGENTS.md" | awk '{print $1}')
    assert_eq "$hash1" "$hash2" "same input should produce identical output"
    teardown_generate_env
}

test_generate_verify_mode_passes_when_clean() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    if bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF" --verify; then
        assert_eq "0" "0" "verify should pass when configs are in sync"
    else
        assert_true "false" "verify should not fail on clean state"
    fi
    teardown_generate_env
}

test_generate_verify_mode_fails_when_drifted() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    # Manually edit a generated file
    echo "# manual edit" >> "$TEST_PROJECT_DIR/AGENTS.md"
    if bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF" --verify 2>/dev/null; then
        assert_true "false" "verify should fail when config has drifted"
    else
        assert_eq "0" "0" "correctly detected drift"
    fi
    teardown_generate_env
}
