#!/usr/bin/env bash

source "$PROJECT_ROOT/lib.sh"

setup_generate_env() {
    export TEST_OUTPUT_DIR="$(mktemp -d)"
    export TEST_PROJECT_DIR="$(mktemp -d)"
    mkdir -p "$TEST_PROJECT_DIR/.claude"
    export TEST_CONF="$(mktemp)"
    cat > "$TEST_CONF" <<CONF
project_roots=$TEST_PROJECT_DIR
CONF
}

teardown_generate_env() {
    rm -rf "$TEST_OUTPUT_DIR" "$TEST_PROJECT_DIR" "$TEST_CONF"
}

test_generate_produces_agents_md() {
    setup_generate_env
    load_config "$TEST_CONF"
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    assert_file_exists "$TEST_PROJECT_DIR/AGENTS.md"
    local content
    content=$(cat "$TEST_PROJECT_DIR/AGENTS.md")
    assert_contains "$content" "Generated by"
    # Verify guardrails.md content is embedded
    assert_contains "$content" "Guardrail" "should embed guardrails.md content"
    teardown_generate_env
}

test_generate_produces_conventions_md() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    assert_file_exists "$TEST_PROJECT_DIR/CONVENTIONS.md"
    local content
    content=$(cat "$TEST_PROJECT_DIR/CONVENTIONS.md")
    assert_contains "$content" "Generated by"
    teardown_generate_env
}

test_generate_produces_cursor_config() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    assert_file_exists "$TEST_PROJECT_DIR/.cursor/rules/guardrails.mdc"
    local content
    content=$(cat "$TEST_PROJECT_DIR/.cursor/rules/guardrails.mdc")
    assert_contains "$content" "Generated by"
    teardown_generate_env
}

test_generate_produces_claude_md() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    assert_file_exists "$TEST_PROJECT_DIR/.claude/CLAUDE.md"
    local content
    content=$(cat "$TEST_PROJECT_DIR/.claude/CLAUDE.md")
    assert_contains "$content" "Generated by"
    teardown_generate_env
}

test_generate_is_deterministic() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    local hash1
    hash1=$(sha256sum "$TEST_PROJECT_DIR/AGENTS.md" | awk '{print $1}')
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    local hash2
    hash2=$(sha256sum "$TEST_PROJECT_DIR/AGENTS.md" | awk '{print $1}')
    assert_eq "$hash1" "$hash2" "same input should produce identical output"
    teardown_generate_env
}

test_generate_verify_mode_passes_when_clean() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    local result=0
    local output
    output=$(bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF" --verify 2>&1) || result=$?
    assert_eq "0" "$result" "verify should exit 0 when configs are in sync"
    assert_contains "$output" "All configs in sync"
    teardown_generate_env
}

test_generate_verify_mode_fails_when_drifted() {
    setup_generate_env
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    # Manually edit a generated file
    echo "# manual edit" >> "$TEST_PROJECT_DIR/AGENTS.md"
    local result=0
    local output
    output=$(bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF" --verify 2>&1) || result=$?
    assert_eq "1" "$result" "verify should exit 1 when config has drifted"
    assert_contains "$output" "drift" "should mention drift in output"
    teardown_generate_env
}

test_generate_multi_project() {
    setup_generate_env
    # Create a second project
    local second_project="$(mktemp -d)"
    mkdir -p "$second_project/.claude"
    cat > "$TEST_CONF" <<CONF
project_roots=$TEST_PROJECT_DIR,$second_project
CONF
    bash "$PROJECT_ROOT/generate-configs.sh" --config "$TEST_CONF"
    # Both projects should get configs
    assert_file_exists "$TEST_PROJECT_DIR/AGENTS.md"
    assert_file_exists "$second_project/AGENTS.md"
    assert_file_exists "$second_project/CONVENTIONS.md"
    assert_file_exists "$second_project/.claude/CLAUDE.md"
    rm -rf "$second_project"
    teardown_generate_env
}

test_generate_rejects_unknown_args() {
    local result=0
    local output
    output=$(bash "$PROJECT_ROOT/generate-configs.sh" --bogus 2>&1) || result=$?
    assert_eq "1" "$result" "should reject unknown arguments"
    assert_contains "$output" "Unknown argument"
}
